services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_DB: '$POSTGRES_DB'
      POSTGRES_USER: '$POSTGRES_USER'
      POSTGRES_PASSWORD: '$POSTGRES_PASSWORD'
      DATABASE_URL: '$DATABASE_URL'
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./scripts/db/mnt:/mnt
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      timeout: 1s
      start_period: 5s
      interval: 1s
      retries: 1000

volumes:
  postgres_data:
